"""
Constants used in traffic simulation
"""

VEHICLE_LENGTH = 0.0045
VEHICLE_SPACING = 0.0005
VEHICLE_TOTAL_SPACE = VEHICLE_LENGTH + VEHICLE_SPACING

JAM_THRESHOLD_DISTANCE = 0.050
DETECTION_DISTANCE = 0.500

BASE_VEHICLE_SPEED = 50.0
SLOW_TRAFFIC_THRESHOLD = 10.0
TRAFFIC_LIGHT_STOPPING_DISTANCE = 0.1

MIN_DENSITY_FACTOR = 0.1
DENSITY_REDUCTION_RATE = 0.15
SECONDS_PER_HOUR = 3600

DEFAULT_SIDE_ROAD_POSITIONS = [1.0, 2.5, 4.0]

BUS_EFFICIENCY_TIME_WEIGHT = 0.7
BUS_EFFICIENCY_SPEED_WEIGHT = 0.3